stages:
- stage: stage1
  jobs:
  - job: A
    steps:
      - script: echo 1; sleep 30

- stage: stage2
  dependsOn: stage1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: B
    steps:
      - script: echo 2
