pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo Building the code!

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo Testing the code!

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
